### ISSUE TITLE
Create responsive styling

### ISSUE THREAD

**Issue by himansu9805** [himansu9805/the-untitled-blog#1]
### CSS for smaller screen devices

Current styling is only compatible with larger screens. Create a new styling which is compatible with devices with smaller screen sizes.

**Comment by himansu9805** [comment]
Sure @Vanfarock, I will assign it to you.

**Comment by Vanfarock** [comment]
Hi @himansu9805, I sent you a pull request with all the change I've made!

If it's not asking too much, could you add "hacktoberfest-accepted" label in my pull request?
There's no problem if you can't, it was funny working on this issue either way.

**Comment by himansu9805** [comment]
Thanks a lot @Vanfarock! I have added the label to your PR. 😄
